services:
  - type: web
    name: eisenhower-matrix-api
    branch: main
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
