services:
  - type: web
    name: eisenhower-matrix-api
    rootDir: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/tasks
